### ISSUE TITLE
Nah cause I would do this if his actions were just, but killing a CEO isn't how you go about that.

### ISSUE THREAD

**Issue by STPv22** [freeluigi/freeluigi.github.io#1]
I like Luigi's motive, and capitalism has fucked over a shit ton of people, but he shouldn't have killed the dude. Also pardoning him isn't in the governor's best intrest because it would put a lack of trust in the justice system, and it would make it seem like the governor condones murder. It would make him look bad. To put it frankly: he killed someone. He is going to be charged, because the law sees it as such. It's sad, but realistic.

**Comment by freeluigi** [comment]
This man fully deserved to die. Denying 1/3 of valid insurance requests is absolutely ridiculous. His death was warranted.
Inviato da iPhone

Il giorno 16 dic 2024, alle ore 1:38 PM, Stpv22 ***@***.***> ha scritto:

﻿

I like Luigi's motive, and capitalism has fucked over a shit ton of people, but he shouldn't have killed the dude. Also pardoning him isn't in the governor's best intrest because it would put a lack of trust in the justice system, and it would make it seem like the governor condones murder. It would make him look bad. To put it frankly: he killed someone. He is going to be charged, because the law sees it as such. It's sad, but realistic.

**Comment by STPv22** [comment]
Might not of been his decision. Unless they are very obviosly evil, someone that has very publicly caused deaths, like trump, they shouldn't have died. People like this just need a "re-education." Also, what about the company's policies? Do they say that the insurance requests are actually covered by them? 

tbh tho he might've deserved to die. My main point is that the governor of PA is unlikely to pardon the dude.

**Comment by STPv22** [comment]
He killed someone, and is going to get the full force of this fucked up jusetice system, especially something as public as this.

**Comment by freeluigi** [comment]
He does deserve it ¯\_(ツ)_/¯
Inviato da iPhone

Il giorno 16 dic 2024, alle ore 6:04 PM, Stpv22 ***@***.***> ha scritto:

﻿

He killed someone, and is going to get the full force of this fucked up jusetice system.

**Comment by freeluigi** [comment]
Doesnt matter if he really gets pardoned or not, its about the fact that the government is corrupt and people do support actions like that.
Inviato da iPhone

Il giorno 16 dic 2024, alle ore 6:03 PM, Stpv22 ***@***.***> ha scritto:

﻿

Might not of been his decision. Unless they are very obviosly evil, someone that has very publicly caused deaths, like trump, they shouldn't have died. People like this just need a "re-education." Also, what about the company's policies? Do they say that the insurance requests are actually covered by them?

tbh tho he might've deserved to die. My main point is that the governor of PA is unlikely to pardon the dude.

**Comment by STPv22** [comment]
I understand, and agree
